sudo: required

language: bash
env:
  DOCKER_COMPOSE_VERSION: 1.9.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

services:
  - docker

script:
    - docker build --no-cache -t dashboard .
    - docker build --no-cache -f appbuilder.Dockerfile -t dashboard-builder
    - docker run --rm dashboard-builder  

# after_success:
#   - >-
#     if [ "$TRAVIS_BRANCH" == "master" ]; then
#     fi
#   - >-
#     if [ "$TRAVIS_BRANCH" == "develop" ]; then
#     fi

