version: '3'
services:
  dashboard:
    build: .
    ports:
      - "8080:8080"
  database:
    image: mysql:8.0.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dashboard
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
